/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 scene.gltf -t -o NewBalance997.tsx 
Author: Isaiah (https://sketchfab.com/aizaisia)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/new-balance-997-05e79a2dffbc4356bba7e0751fada08f
Title: New Balance 997
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Shoe_set_02_Sole_0: THREE.Mesh
    Shoe_set_02_Outer_0: THREE.Mesh
    Shoe_set_02_Laces_0: THREE.Mesh
    Shoe_set_02_Inner_0: THREE.Mesh
  }
  materials: {
    Sole: THREE.MeshStandardMaterial
    Outer: THREE.MeshStandardMaterial
    Laces: THREE.MeshStandardMaterial
    Inner: THREE.MeshStandardMaterial
  }
  // animations: GLTFAction[]
}

export function NewBalance997(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/nw-997/scene.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group scale={[0.2,0.2,0.2]}>
          <mesh geometry={nodes.Shoe_set_02_Sole_0.geometry} material={materials.Sole} />
          <mesh geometry={nodes.Shoe_set_02_Outer_0.geometry} material={materials.Outer} />
          <mesh geometry={nodes.Shoe_set_02_Laces_0.geometry} material={materials.Laces} />
          <mesh geometry={nodes.Shoe_set_02_Inner_0.geometry} material={materials.Inner} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
