/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 scene.gltf -t -o Basketball.tsx 
Author: 24fpsboy (https://sketchfab.com/ikagogava)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/basketball-eb172b5f4e544f428c2bcd8d3f067a91
Title: Basketball
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import withBounceAndRollAnimation from './hocs/withBounceAndRollAnimation'

type GLTFResult = GLTF & {
  nodes: {
    defaultMaterial: THREE.Mesh
  }
  materials: {
    None: THREE.MeshStandardMaterial
  }
  // animations: GLTFAction[]
}

const Basketball: React.FC<JSX.IntrinsicElements['group']> = (props) => {
  const { nodes, materials } = useGLTF('/basketball/scene.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.defaultMaterial.geometry} material={materials.None} rotation={[Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

export default withBounceAndRollAnimation(Basketball);

useGLTF.preload('/scene.gltf')
