/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 scene.gltf -t -o ShoeBox.tsx 
Author: DeezVertz (https://sketchfab.com/DeezVertz)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/nike-air-jordan-1-fbe52211197c4b449f29de5aa4eb0611
Title: Nike Air Jordan 1
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Shoe_L_MAT_Shoe_L_0: THREE.Mesh
    Sole_L_MAT_Sole_L_0: THREE.Mesh
    Laces_L_MAT_Laces_L_0: THREE.Mesh
    Laces_R_MAT_Laces_R_0: THREE.Mesh
    Shoe_R_MAT_Shoe_R_0: THREE.Mesh
    Sole_R_MAT_Sole_R_0: THREE.Mesh
    BoxBottom_BoxBottom_0: THREE.Mesh
    BoxTop_BoxTop_0: THREE.Mesh
  }
  materials: {
    MAT_Shoe_L: THREE.MeshStandardMaterial
    MAT_Sole_L: THREE.MeshStandardMaterial
    MAT_Laces_L: THREE.MeshStandardMaterial
    MAT_Laces_R: THREE.MeshStandardMaterial
    MAT_Shoe_R: THREE.MeshStandardMaterial
    MAT_Sole_R: THREE.MeshStandardMaterial
    BoxBottom: THREE.MeshStandardMaterial
    BoxTop: THREE.MeshStandardMaterial
  }
  // animations: GLTFAction[]
}

export function ShoeBox(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/shoe-box/scene.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-5.196, 11.19, -1.093]} rotation={[Math.PI, -0.132, Math.PI]}>
          <mesh castShadow geometry={nodes.Shoe_L_MAT_Shoe_L_0.geometry} material={materials.MAT_Shoe_L} />
          <mesh castShadow geometry={nodes.Sole_L_MAT_Sole_L_0.geometry} material={materials.MAT_Sole_L} />
          <mesh castShadow geometry={nodes.Laces_L_MAT_Laces_L_0.geometry} material={materials.MAT_Laces_L} />
        </group>
        <group position={[0.109, 0, 0.656]} rotation={[0, 0.101, 0]}>
          <mesh castShadow geometry={nodes.Laces_R_MAT_Laces_R_0.geometry} material={materials.MAT_Laces_R} position={[4.983, 11.189, 0]} rotation={[0, 0.145, 0]} />
          <mesh castShadow geometry={nodes.Shoe_R_MAT_Shoe_R_0.geometry} material={materials.MAT_Shoe_R} position={[4.983, 11.189, 0]} rotation={[0, 0.145, 0]} />
          <mesh castShadow geometry={nodes.Sole_R_MAT_Sole_R_0.geometry} material={materials.MAT_Sole_R} position={[4.983, 11.189, 0]} rotation={[0, 0.145, 0]} />
        </group>
        <mesh castShadow geometry={nodes.BoxBottom_BoxBottom_0.geometry} material={materials.BoxBottom} rotation={[0, -Math.PI / 2, 0]} scale={0.956} />
        <mesh castShadow geometry={nodes.BoxTop_BoxTop_0.geometry} material={materials.BoxTop} rotation={[0, -1.566, 0]} scale={0.956} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
